### PR TITLE
Add Microdata API tests

### PR DESCRIPTION
**Pull request by termi**

### CODE REVIEW

**Comment by Raynos** [comment]
Can you change the namespace from DOM to HTML5 or HTML or better yet MicroData. 

The DOM namespace `feature["DOM.` should only be used for things in the DOM specification.

**Comment by termi** [comment]
"HTML5.Microdata" ?

**Comment by termi** [comment]
What should do I do with document.getItems ?
And with DocumentFragment.getItems ?

**Comment by Raynos** [comment]
`HTML.Microdata.Document.getItems`, `HTML.Microdata.DocumentFragment.getItems`, `HTML.Microdata.Element.itemId` those seem fine to me.

**Pull request merged**
